name: Release
on:
  push:
    branches: [scala-cli-v0]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v12
      - uses: olafurpg/setup-gpg@v3
      - uses: coursier/cache-action@v6.1
      - name: Publish
        run: |
          sbt ci-release
        env:
          GIT_USER: scalameta@scalameta.org
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
